### ISSUE TITLE
Midterm-Slicing

### ISSUE THREAD

**Issue by mxistrissongpanya-matc** [madisoncollege-it-programs/python-scripting-mxistrissongpanya-matc#10]
Finished. Ready for grading. Thank you

**Comment by cethenmc** [comment]
Really nice work on this Midterm part overall.  A couple of specifics:  1. the section you labeled as creating variables to slice was not creating variables at all.  I won't take off because you created the string variables just below.  However, the assignment did not ask for you to print them (1 pt).  2. the String1 did not follow the request precisely…instead of going from the end of the file, you switched to positive values (1 pt).  3. you repeated 4d twice, which inserted extra words in the quote (2 pt).  Thanks for keeping the code nice and clean!  30/34
