### ISSUE TITLE
Midterm-Jurassic park

### ISSUE THREAD

**Issue by mxistrissongpanya-matc** [madisoncollege-it-programs/python-scripting-mxistrissongpanya-matc#8]
Jurassic park midterm ready for grading. Please read email about other assignments.

**Comment by cethenmc** [comment]
There were not three tries allowed for logging in.  The user receives the right text, but it ends the program before allowing two more tries.  White_rabit was never used after instantiation  (6 pts).  The comparison on line 32 was programmed incorrectly, but it was a nice idea to try to use the values (2 pts).  In line 36, keys were to be extracted from the command_database dictionary (2 pts).  Lines 40-45 could have been done more easily using the input to look up received to find the value. I will take less off because I believe your actions were to demonstrate your understanding of 3.iv.  However that could be simplified since three of the things do the same thing [meaning pull its value from the dictionary] (2 pts).  Your score for this part is 21/33
